config_path: outputs/training/3dgs_res_704_1280_views_121_multi_6/config.yaml
out_dir_inference: outputs/inference/3dgs_res_704_1280_views_121_multi_6

static_view_indices_fixed: ['5', '0', '1', '2', '3', '4']
target_index_subsample: 4